
Key: 7IEKi9T3N6n

Spawn:
  teleportToSpawnJoin: true
  Sound-enable: true
  Sound: BLOCK_NOTE_PLING
  Location:
    world: "world"
    x : 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
  Messages:
    reloadPlugin: "§fПлагин был §aперезагружен."
    noPerm: "§cНет прав на команду."
    noPermSet: "§cНет прав на установку спавна."
    setSpawn: "§fCпавн был §aустановлен."
    tpSpawn: "§fТы был §aтелепортирован §fна спавн."
    consoleSend: "§cОшибка! Команда только для игрока."
    notFoundPlayer: "§fИгрок не найден"
    slaveTeleport: "§fТебя §aтелепортировали §fна спавн!"

Void:
  Messages:
    reload: "хехе, плагин был растартнут."
  Command: "say лох добра"
  World: "world"
  Y: 10
