name: MWCore
version: '1.1.2'
main: ru.bodi.mineworld.core.main
authors: [ BodiMastiff ]
description: for mineworld. by bodimastiff
commands:
  spawn:
    aliases:
      - спавн
      - ызфцт
      - msp
  mwvoid:
    aliases:
      - void
      - мщшв
      - mvd
  MWcore: